# Prepare df_ssp for plots and stats

In [1]:
# import all packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

import plotly.express as px
import plotly.graph_objects as go

In [2]:
import os
print(os.getcwd())
os.chdir(r"C:\Users\User\Desktop\Work\Infra_Data_April2026")
print(os.getcwd())

c:\Users\User\Desktop\Work\Infra_Data_April2026\scripts\plots_stats
C:\Users\User\Desktop\Work\Infra_Data_April2026

### Import output data for all SSPs

In [3]:
from scripts.plots_stats.get_df_ssp import get_df_ssp
df_ssp = get_df_ssp()

(30533, 17) (31179, 10)
Total number of cities 30498

In [4]:
df_ssp['STATEFP'].unique()

array(['04', '06', '08', '09', '10', '11', '12', '13', '15', '17', '19',
       '22', '23', '24', '25', '26', '27', '29', '32', '34', '36', '39',
       '41', '42', '44', '48', '49', '50', '51', '53', '55', '01', '05',
       '16', '18', '20', '21', '28', '30', '31', '33', '35', '37', '38',
       '40', '45', '46', '47', '54', '56'], dtype=object)

In [5]:
# df_ssp.columns[40:] #[['GEOID', 'NAMELSAD', 'city type', 'REGION', 'CensusPop_20','length_m_perCap_2020_ssp2']].sort_values('length_m_perCap_2020_ssp2').head(10)

### Percent cities with increasing burden from 2020 to 2100

In [6]:
print('Cities with an increasing burden at each scenario ====')
print("For buildings=== ssp2, ssp1 , ssp4 ")
print(df_ssp[df_ssp['volume_m3_perCap_2020_ssp2'] < df_ssp['volume_m3_perCap_2100_ssp2']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp2'].shape[0]) #,\
#      df_ssp[df_ssp['volume_m3_perCap_2020_ssp1'] < df_ssp['volume_m3_perCap_2100_ssp1']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp1'].shape[0],  \
#         df_ssp[df_ssp['volume_m3_perCap_2020_ssp4'] < df_ssp['volume_m3_perCap_2100_ssp4']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp4'].shape[0])
print("For roadways=== ssp2, ssp1 , ssp4 ")
print(df_ssp[df_ssp['length_m_perCap_2020_ssp2'] < df_ssp['length_m_perCap_2100_ssp2']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp2'].shape[0]) #, \
# df_ssp[df_ssp['length_m_perCap_2020_ssp1'] < df_ssp['length_m_perCap_2100_ssp1']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp1'].shape[0], \
# df_ssp[df_ssp['length_m_perCap_2020_ssp4'] < df_ssp['length_m_perCap_2100_ssp4']].shape[0] / df_ssp['volume_m3_perCap_2100_ssp4'].shape[0] )

Cities with an increasing burden at each scenario ====
For buildings=== ssp2, ssp1 , ssp4
0.5259033379237983
For roadways=== ssp2, ssp1 , ssp4
0.5553151026296806

### Regional decriptive stats by city type

In [7]:
df_ssp.groupby(['city type','REGION'])[['volume_m3_perCap_2020_ssp2','length_m_perCap_2020_ssp2']].median().sort_values(['city type','volume_m3_perCap_2020_ssp2']).round(2)

                     volume_m3_perCap_2020_ssp2  length_m_perCap_2020_ssp2
city type REGION
periurban Northeast                      614.32                      15.83
          South                          698.27                      22.52
          West                           770.94                      16.65
          Midwest                        785.48                      19.88
rural     Northeast                      549.45                      27.11
          South                          764.25                      50.25
          Midwest                        799.42                      43.28
          West                           860.19                      58.81
suburban  Northeast                      700.97                      13.17
          West                           862.38                      12.75
          South                          877.10                      18.20
          Midwest                        914.24                      15.61
urban     Northeast                      543.38                       4.73
          West                           603.54                       4.25
          Midwest                        694.07                       5.69
          South                          694.31                       5.67

In [8]:
df_ssp.groupby(['city type'])[['volume_m3_perCap_2020_ssp2','length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2','length_m_perCap_2100_ssp2']].median().sort_values(['city type','volume_m3_perCap_2020_ssp2']).round(2)

,volume_m3_perCap_2020_ssp2,length_m_perCap_2020_ssp2,length_m_perCap_2050_ssp2,length_m_perCap_2100_ssp2
city type,,,,
periurban,720.70,19.30,18.12,18.08
rural,766.93,45.52,47.84,57.14
suburban,837.33,15.29,14.36,14.06
urban,593.51,4.70,4.23,3.95

In [9]:
45.52/4.7, 45.52/19.30

(9.685106382978724, 2.3585492227979277)

### Cities with less than 1000 m/person roadway

In [10]:
df_ssp[df_ssp['length_m_perCap_2020_ssp2']<1000].sort_values('length_m_perCap_2020_ssp2').tail(100)['length_m_perCap_2100_ssp2'].describe().round()

count     100.0
mean      931.0
std       398.0
min       416.0
25%       650.0
50%       829.0
75%      1088.0
max      2617.0
Name: length_m_perCap_2100_ssp2, dtype: float64

In [11]:
df_ssp['length_m_perCap_2020_ssp2'].quantile([.5,.95]), df_ssp[df_ssp['length_m_perCap_2020_ssp2']<1000]['length_m_perCap_2020_ssp2'].quantile([.5,.95])

(0.50     29.800670
 0.95    156.482043
 Name: length_m_perCap_2020_ssp2, dtype: float64,
 0.50     29.752557
 0.95    154.179625
 Name: length_m_perCap_2020_ssp2, dtype: float64)

### Cities with over 1000 m/person roadway

In [12]:
df_ssp[df_ssp['length_m_perCap_2020_ssp2']>1000].shape #sort_values('length_m_perCap_2020_ssp2')[['GEOID','NAMELSAD', 'median_income']].head(50)

(45, 118)

### Cities with less than 100 m3/person built volume

In [13]:
df_ssp[df_ssp['volume_m3_perCap_2020_ssp2']<100].sort_values('length_m_perCap_2020_ssp2')[['GEOID','NAMELSAD', 'median_income']].head(50)

         GEOID                               NAMELSAD  median_income
4473   3667367                      Siena College CDP            NaN
1141   0963313              Quinnipiac University CDP            NaN
5907   4278698  University of Pittsburgh Bradford CDP            NaN
5810   4248868                    Messiah College CDP       250001.0
4492   3672327                        SUNY Oswego CDP            NaN
4328   3626561                        Forest Home CDP        62425.0
14642  0686489          Woodville Farm Labor Camp CDP        33750.0
8545   1506300                       East Kapolei CDP        79280.0
12439  5142501                            Kincora CDP            NaN
15627  1579250                            Wainiha CDP       108750.0
15603  1550150                           Maunaloa CDP        35208.0
26014  4251568                   Mount Gretna borough       136563.0
7757   0642510                            Lompico CDP        90417.0
14493  0658456                      Post Mountain CDP        17000.0
14378  0642384                           Loma Mar CDP       246094.0

### Cities with over 2000 m3/person built volume

In [14]:
# df_ssp[df_ssp['volume_m3_perCap_2020_ssp2']>2000][['NAMELSAD', 'REGION','city type', 'median_income']]

In [15]:
df_ssp[df_ssp['RBUV_Burden_2050'] == 'increasingBurden'][['volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2']].median(), \
df_ssp[df_ssp['RBUV_Burden_2100'] == 'increasingBurden'][['volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2']].median()

(volume_m3_perCap_2020_ssp2     763.484339
 volume_m3_perCap_2050_ssp2    1221.670377
 dtype: float64,
 volume_m3_perCap_2050_ssp2     835.517310
 volume_m3_perCap_2100_ssp2    1046.198219
 dtype: float64)

In [16]:
1221-763, 1046-835, (1221-763)*100/763, (1046-763)*100/763,

(458, 211, 60.026212319790304, 37.09043250327654)

In [17]:
df_ssp[df_ssp['RL_Burden_2050'] == 'increasingBurden'][['length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2']].median(), \
df_ssp[df_ssp['RL_Burden_2100'] == 'increasingBurden'][['length_m_perCap_2050_ssp2','length_m_perCap_2100_ssp2']].median()

(length_m_perCap_2020_ssp2    42.219391
 length_m_perCap_2050_ssp2    47.923631
 dtype: float64,
 length_m_perCap_2050_ssp2    41.372511
 length_m_perCap_2100_ssp2    52.986012
 dtype: float64)

In [18]:
47.9-42.2, 53-41.4, (47.9-42.2)*100/42.2, (53-42.2)*100/42.2

(5.699999999999996, 11.600000000000001, 13.507109004739325, 25.592417061611368)

In [19]:
df_ssp[df_ssp['RBUV_Burden_2050'] == 'decreasingBurden'][['volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2']].median(), \
df_ssp[df_ssp['RBUV_Burden_2100'] == 'decreasingBurden'][['volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2']].median()

(volume_m3_perCap_2020_ssp2    778.581150
 volume_m3_perCap_2050_ssp2    651.119495
 dtype: float64,
 volume_m3_perCap_2050_ssp2    681.681191
 volume_m3_perCap_2100_ssp2    612.644072
 dtype: float64)

In [20]:
(778.6-651.1), (681.7-612.6), (778.6-651.1)*100/778.6, (778.6-612.6)*100/778.6

(127.5, 69.10000000000002, 16.375545851528383, 21.320318520421267)

In [21]:
df_ssp[df_ssp['RL_Burden_2050'] == 'decreasingBurden'][['length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2']].median(), \
df_ssp[df_ssp['RL_Burden_2100'] == 'decreasingBurden'][['length_m_perCap_2050_ssp2','length_m_perCap_2100_ssp2']].median()

(length_m_perCap_2020_ssp2    23.234210
 length_m_perCap_2050_ssp2    20.956989
 dtype: float64,
 length_m_perCap_2050_ssp2    20.855517
 length_m_perCap_2100_ssp2    18.627258
 dtype: float64)

In [22]:
23.234210-20.956989, 20.855517-18.627258, (23.234210-20.956989)*100/23.234210, (23.234210-18.627258)*100/23.234210

(2.277221000000001, 2.2282589999999978, 9.801155279219739, 19.828313508399898)

In [23]:
df_ssp[df_ssp['GEOID']=='1765000'][['CensusPop_20', 'NAMELSAD', 'REGION', 'city type','RL_Burden_2050','RL_Burden_2100', 'RBUV_Burden_2050', 'RBUV_Burden_2100',
                                    'volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2',
                                    'length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2','length_m_perCap_2100_ssp2']].round(2)

,CensusPop_20,NAMELSAD,REGION,city type,RL_Burden_2050,RL_Burden_2100,RBUV_Burden_2050,RBUV_Burden_2100,volume_m3_perCap_2020_ssp2,volume_m3_perCap_2050_ssp2,volume_m3_perCap_2100_ssp2,length_m_perCap_2020_ssp2,length_m_perCap_2050_ssp2,length_m_perCap_2100_ssp2
1909,148655,Rockford city,Midwest,suburban,noChange,noChange,decreasingBurden,increasingBurden,1097.27,1035.95,1084.01,12.54,12.55,13.13

In [24]:
df_ssp[df_ssp['GEOID']=='1718823'][['CensusPop_20', 'NAMELSAD', 'REGION', 'city type','RL_Burden_2050','RL_Burden_2100', 'RBUV_Burden_2050', 'RBUV_Burden_2100',
                                    'volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2',
                                     'length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2','length_m_perCap_2100_ssp2']].round(2)

,CensusPop_20,NAMELSAD,REGION,city type,RL_Burden_2050,RL_Burden_2100,RBUV_Burden_2050,RBUV_Burden_2100,volume_m3_perCap_2020_ssp2,volume_m3_perCap_2050_ssp2,volume_m3_perCap_2100_ssp2,length_m_perCap_2020_ssp2,length_m_perCap_2050_ssp2,length_m_perCap_2100_ssp2
1886,70522,Decatur city,Midwest,suburban,increasingBurden,increasingBurden,increasingBurden,increasingBurden,1347.85,1570.51,2998.97,16.05,21.28,40.63

In [25]:
df_ssp[['volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2','length_m_perCap_2020_ssp2']].describe()

,volume_m3_perCap_2020_ssp2,volume_m3_perCap_2050_ssp2,volume_m3_perCap_2100_ssp2,length_m_perCap_2020_ssp2
count,30498.000000,30498.000000,30498.000000,30498.000000
mean,898.715703,1293.268299,1490.083593,52.583272
std,2226.051709,2222.922568,2731.592644,122.185553
min,12.425720,40.126668,34.443737,0.010721
25%,582.984951,549.983826,564.982813,16.870785
50%,772.854334,770.215376,846.558551,29.800670
75%,1023.319295,1145.365498,1355.173895,53.616601
max,341691.085869,75617.381782,113426.072674,8178.395442

In [26]:
df_ssp[['volume_m3_perCap_2020_ssp2', 'length_m_perCap_2020_ssp2']].quantile([.5,.95,1])

      volume_m3_perCap_2020_ssp2  length_m_perCap_2020_ssp2
0.50                  772.854334                  29.800670
0.95                 1620.748263                 156.482043
1.00               341691.085869                8178.395442

In [27]:
# df_ssp[df_ssp['volume_m3_perCap_2020_ssp2']<100]#.shape, 29751/30498
# df_ssp[df_ssp['length_m_perCap_2020_ssp2']>1000]#.groupby('REGION').count()#.shape, 29751/30498

In [28]:
df_ssp.shape, df_ssp['STATEFP'].nunique()

((30498, 118), 50)

In [29]:
print(f"Cities with less than 100 cubic meter/person RBUV:==  {df_ssp[df_ssp['volume_m3_perCap_2020_ssp2'] < 100].shape[0]}")
print(f"Cities with less than 10 m/person roadway:==          {df_ssp[df_ssp['length_m_perCap_2020_ssp2'] < 10].shape[0]}")
print(f"Cities with over 1000 m/person roadway:==             {df_ssp[df_ssp['length_m_perCap_2020_ssp2'] > 1000].shape[0]}")

Cities with less than 100 cubic meter/person RBUV:==  15
Cities with less than 10 m/person roadway:==          2609
Cities with over 1000 m/person roadway:==             45

In [30]:
df_ssp['RBUV_Burden_2050'].value_counts(), df_ssp['RL_Burden_2050'].value_counts(), df_ssp['RBUV_Burden_2100'].value_counts(), df_ssp['RL_Burden_2100'].value_counts()

(RBUV_Burden_2050
 decreasingBurden    19445
 increasingBurden    10990
 noChange               63
 Name: count, dtype: int64,
 RL_Burden_2050
 decreasingBurden    13762
 increasingBurden    12866
 noChange             3870
 Name: count, dtype: int64,
 RBUV_Burden_2100
 increasingBurden    18047
 decreasingBurden    12347
 noChange              104
 Name: count, dtype: int64,
 RL_Burden_2100
 increasingBurden    17193
 decreasingBurden     9713
 noChange             3592
 Name: count, dtype: int64)

In [31]:
10990/30498, 12866/30498, 18047/30498, 17193/30498

(0.36035149845891534,
 0.4218637287690996,
 0.5917437208997312,
 0.5637418847137518)

In [32]:
df_ssp[(df_ssp['RBUV_Burden_2050'] =='decreasingBurden') & (df_ssp['RBUV_Burden_2100'] =='increasingBurden') ].shape[0]/df_ssp.shape[0],\
df_ssp[(df_ssp['RL_Burden_2050'] =='decreasingBurden') & (df_ssp['RL_Burden_2100'] =='increasingBurden') ].shape[0]/df_ssp.shape[0]

(0.30283953046101386, 0.07872647386713882)

In [33]:
df_ssp.groupby('STATEFP')[[ 'volume_m3_perCap_2020_ssp2','volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2','added_RBUV_2020_2050', 'added_RBUV_2050_2100',
                            'length_m_perCap_2020_ssp2','length_m_perCap_2050_ssp2', 'length_m_perCap_2100_ssp2','added_RL_2020_2050',
                            'added_RL_2050_2100']].median().round(1).to_csv(r'outputfiles\csvs\state_level_median.csv')

In [34]:
df_ssp[(df_ssp['CensusPop_20']<=10000)].groupby(['STATEFP'])[['volume_m3_perCap_2020_ssp2','volume_m3_perCap_2050_ssp2','volume_m3_perCap_2100_ssp2','length_m_perCap_2020_ssp2',
                                                              'length_m_perCap_2050_ssp2', 'length_m_perCap_2100_ssp2', 'added_RBUV_2020_2050', 'added_RL_2020_2050',
                         'added_RBUV_2050_2100', 'added_RL_2050_2100']].median().round(2).to_csv(r'outputfiles\csvs\state_level_median_below_10000.csv')

### Constantly increasing burden

In [35]:
condition = (df_ssp['volume_m3_perCap_2020_ssp2'] < df_ssp['volume_m3_perCap_2030_ssp2']) & (df_ssp['volume_m3_perCap_2030_ssp2'] < df_ssp['volume_m3_perCap_2040_ssp2']) & \
(df_ssp['volume_m3_perCap_2040_ssp2'] < df_ssp['volume_m3_perCap_2050_ssp2']) & (df_ssp['volume_m3_perCap_2050_ssp2'] < df_ssp['volume_m3_perCap_2060_ssp2']) & \
(df_ssp['volume_m3_perCap_2060_ssp2'] < df_ssp['volume_m3_perCap_2070_ssp2']) & (df_ssp['volume_m3_perCap_2070_ssp2'] < df_ssp['volume_m3_perCap_2080_ssp2']) & \
(df_ssp['volume_m3_perCap_2080_ssp2'] < df_ssp['volume_m3_perCap_2090_ssp2']) & (df_ssp['volume_m3_perCap_2090_ssp2'] < df_ssp['volume_m3_perCap_2100_ssp2'])
print(f"cities that face constantly increasing burden for RBUV {np.round(df_ssp[condition].shape[0]*100/df_ssp.shape[0],2)}")

condition = (df_ssp['length_m_perCap_2020_ssp2'] < df_ssp['length_m_perCap_2030_ssp2']) & (df_ssp['length_m_perCap_2030_ssp2'] < df_ssp['length_m_perCap_2040_ssp2']) & \
(df_ssp['length_m_perCap_2040_ssp2'] < df_ssp['length_m_perCap_2050_ssp2']) & (df_ssp['length_m_perCap_2050_ssp2'] < df_ssp['length_m_perCap_2060_ssp2']) & \
(df_ssp['length_m_perCap_2060_ssp2'] < df_ssp['length_m_perCap_2070_ssp2']) & (df_ssp['length_m_perCap_2070_ssp2'] < df_ssp['length_m_perCap_2080_ssp2']) & \
(df_ssp['length_m_perCap_2080_ssp2'] < df_ssp['length_m_perCap_2090_ssp2']) & (df_ssp['length_m_perCap_2090_ssp2'] < df_ssp['length_m_perCap_2100_ssp2'])
print(f"cities that face constantly increasing burden for RL {np.round(df_ssp[condition].shape[0]*100/df_ssp.shape[0],2)}")

cities that face constantly increasing burden for RBUV 10.11
cities that face constantly increasing burden for RL 31.1

In [36]:
df_ssp.filter(regex='volume').columns
print("Percent cities with increasing built volumes thereby increasing burden")

column_nmaes1 = ['volume_m3_perCap_2020_ssp2','volume_m3_perCap_2030_ssp2', 'volume_m3_perCap_2040_ssp2','volume_m3_perCap_2050_ssp2', 'volume_m3_perCap_2060_ssp2',
                'volume_m3_perCap_2070_ssp2', 'volume_m3_perCap_2080_ssp2', 'volume_m3_perCap_2090_ssp2']
column_nmaes2 = ['volume_m3_perCap_2030_ssp2', 'volume_m3_perCap_2040_ssp2','volume_m3_perCap_2050_ssp2', 'volume_m3_perCap_2060_ssp2',
                'volume_m3_perCap_2070_ssp2', 'volume_m3_perCap_2080_ssp2', 'volume_m3_perCap_2090_ssp2', 'volume_m3_perCap_2100_ssp2']
for col1, col2 in zip(column_nmaes1, column_nmaes2):
    print(np.round(df_ssp[df_ssp[col2] > df_ssp[col1]].shape[0]*100/df_ssp.shape[0],2))

print("Percent cities with increasing roadways thereby increasing burden")

column_nmaes1 = ['length_m_perCap_2020_ssp2','length_m_perCap_2030_ssp2', 'length_m_perCap_2040_ssp2','length_m_perCap_2050_ssp2', 
                 'length_m_perCap_2060_ssp2','length_m_perCap_2070_ssp2', 'length_m_perCap_2080_ssp2', 'length_m_perCap_2090_ssp2']
column_nmaes2 = ['length_m_perCap_2030_ssp2', 'length_m_perCap_2040_ssp2','length_m_perCap_2050_ssp2', 'length_m_perCap_2060_ssp2',
                 'length_m_perCap_2070_ssp2', 'length_m_perCap_2080_ssp2', 'length_m_perCap_2090_ssp2', 'length_m_perCap_2100_ssp2']
for col1, col2 in zip(column_nmaes1, column_nmaes2):
    print(np.round(df_ssp[df_ssp[col2] > df_ssp[col1]].shape[0]*100/df_ssp.shape[0],2))

Percent cities with increasing built volumes thereby increasing burden
22.56
45.9
51.1
48.21
49.82
56.19
64.34
71.63
Percent cities with increasing roadways thereby increasing burden
33.33
46.93
52.09
49.37
50.97
57.12
65.21
72.4

### Constandtly decreasing burden

In [37]:
condition = (df_ssp['volume_m3_perCap_2020_ssp2'] > df_ssp['volume_m3_perCap_2030_ssp2']) & (df_ssp['volume_m3_perCap_2030_ssp2'] > df_ssp['volume_m3_perCap_2040_ssp2']) & \
            (df_ssp['volume_m3_perCap_2040_ssp2'] > df_ssp['volume_m3_perCap_2050_ssp2']) & (df_ssp['volume_m3_perCap_2050_ssp2'] > df_ssp['volume_m3_perCap_2060_ssp2']) & \
            (df_ssp['volume_m3_perCap_2060_ssp2'] > df_ssp['volume_m3_perCap_2070_ssp2']) & (df_ssp['volume_m3_perCap_2070_ssp2'] > df_ssp['volume_m3_perCap_2080_ssp2']) & \
            (df_ssp['volume_m3_perCap_2080_ssp2'] > df_ssp['volume_m3_perCap_2090_ssp2']) & (df_ssp['volume_m3_perCap_2090_ssp2'] > df_ssp['volume_m3_perCap_2100_ssp2'])
print(f"cities that face constantly decreasing burden for RBUV {np.round(df_ssp[condition].shape[0]*100/df_ssp.shape[0],2)}")

condition = (df_ssp['length_m_perCap_2020_ssp2'] > df_ssp['length_m_perCap_2030_ssp2']) & (df_ssp['length_m_perCap_2030_ssp2'] > df_ssp['length_m_perCap_2040_ssp2']) & \
            (df_ssp['length_m_perCap_2040_ssp2'] > df_ssp['length_m_perCap_2050_ssp2']) & (df_ssp['length_m_perCap_2050_ssp2'] > df_ssp['length_m_perCap_2060_ssp2']) & \
            (df_ssp['length_m_perCap_2060_ssp2'] > df_ssp['length_m_perCap_2070_ssp2']) & (df_ssp['length_m_perCap_2070_ssp2'] > df_ssp['length_m_perCap_2080_ssp2']) & \
            (df_ssp['length_m_perCap_2080_ssp2'] > df_ssp['length_m_perCap_2090_ssp2']) & (df_ssp['length_m_perCap_2090_ssp2'] > df_ssp['length_m_perCap_2100_ssp2'])
print(f"cities that face constantly decreasing burden for RL {np.round(df_ssp[condition].shape[0]*100/df_ssp.shape[0],2)}")

cities that face constantly decreasing burden for RBUV 20.83
cities that face constantly decreasing burden for RL 25.63

In [38]:
df_ssp.filter(regex='volume').columns
print("Percent cities with decreasing built volumes")

column_nmaes1 = ['volume_m3_perCap_2020_ssp2','volume_m3_perCap_2030_ssp2', 'volume_m3_perCap_2040_ssp2','volume_m3_perCap_2050_ssp2', 'volume_m3_perCap_2060_ssp2',
                'volume_m3_perCap_2070_ssp2', 'volume_m3_perCap_2080_ssp2', 'volume_m3_perCap_2090_ssp2']
column_nmaes2 = ['volume_m3_perCap_2030_ssp2', 'volume_m3_perCap_2040_ssp2','volume_m3_perCap_2050_ssp2', 'volume_m3_perCap_2060_ssp2',
                'volume_m3_perCap_2070_ssp2', 'volume_m3_perCap_2080_ssp2', 'volume_m3_perCap_2090_ssp2', 'volume_m3_perCap_2100_ssp2']
for col1, col2 in zip(column_nmaes1, column_nmaes2):
    print(np.round(df_ssp[df_ssp[col2] < df_ssp[col1]].shape[0]*100/df_ssp.shape[0],2))

print("Percent cities with decreasing roadways")

column_nmaes1 = ['length_m_perCap_2020_ssp2','length_m_perCap_2030_ssp2', 'length_m_perCap_2040_ssp2','length_m_perCap_2050_ssp2', 
                 'length_m_perCap_2060_ssp2','length_m_perCap_2070_ssp2', 'length_m_perCap_2080_ssp2', 'length_m_perCap_2090_ssp2']
column_nmaes2 = ['length_m_perCap_2030_ssp2', 'length_m_perCap_2040_ssp2','length_m_perCap_2050_ssp2', 'length_m_perCap_2060_ssp2',
                 'length_m_perCap_2070_ssp2', 'length_m_perCap_2080_ssp2', 'length_m_perCap_2090_ssp2', 'length_m_perCap_2100_ssp2']
for col1, col2 in zip(column_nmaes1, column_nmaes2):
    print(np.round(df_ssp[df_ssp[col2] < df_ssp[col1]].shape[0]*100/df_ssp.shape[0],2))

Percent cities with decreasing built volumes
77.44
52.16
47.52
50.89
48.85
42.5
34.31
27.31
Percent cities with decreasing roadways
66.58
52.86
47.82
50.5
48.9
42.82
34.65
27.51

In [ ]:
df_ssp.groupby('STATEFP')[['volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2050_ssp2', 'volume_m3_perCap_2100_ssp2', 'added_RBUV_2020_2050', 'added_RBUV_2050_2100',
                           'length_m_perCap_2020_ssp2', 'length_m_perCap_2050_ssp2', 'length_m_perCap_2100_ssp2','added_RL_2020_2050',
                           'added_RL_2050_2100']].median().to_csv(r"C:\Users\User\Desktop\Work\Infra_Data_April2026\medianPerCapbyState.csv")

In [38]:
df_ssp[['GEOID', 'NAMELSAD', 'city type', 'REGION','label', 'future trend from SSP 2',
    'CensusPop_20','ssp22030', 'ssp22040', 'ssp22050','ssp22060',
       'ssp22070', 'ssp22080', 'ssp22090', 'ssp22100' ,'volume_m3_perCap_2020_ssp2', 'volume_m3_perCap_2030_ssp2',
       'volume_m3_perCap_2040_ssp2', 'volume_m3_perCap_2050_ssp2',
       'volume_m3_perCap_2060_ssp2', 'volume_m3_perCap_2070_ssp2',
       'volume_m3_perCap_2080_ssp2', 'volume_m3_perCap_2090_ssp2',
       'volume_m3_perCap_2100_ssp2','length_m_perCap_2020_ssp2',
       'length_m_perCap_2030_ssp2', 'length_m_perCap_2040_ssp2',
       'length_m_perCap_2050_ssp2', 'length_m_perCap_2060_ssp2',
       'length_m_perCap_2070_ssp2', 'length_m_perCap_2080_ssp2',
       'length_m_perCap_2090_ssp2', 'length_m_perCap_2100_ssp2',
       'weighted_HU_density_sqmi', 
       'RBUV_Burden_2050', 'RBUV_Burden_2100','RL_Burden_2050', 'RL_Burden_2100']].to_csv(r'outputfiles\csvs\df_ssp2_clean.csv')

### Change in degree of urbanization over time

In [39]:
# df_city_type = pd.read_csv(r'outputfiles\csvs\output_city_type_ssp2.csv')

# df_city_type[['city type',
#        'citytype_at_2030', 'citytype_at_2040', 'citytype_at_2050',
#        'citytype_at_2060', 'citytype_at_2070', 'citytype_at_2080',
#        'citytype_at_2090', 'citytype_at_2100']].apply(pd.Series.value_counts).T

In [40]:
# 338-312, 373-338, 26+35

In [41]:
# df_city_type['GEOID'] = df_city_type['GEOID'].astype(str).str.zfill(7)

In [42]:
# df_city_type = df_city_type.merge(df_ssp[['GEOID','REGION', 'ALAND', 'CensusPop_20']], on = 'GEOID', how = 'left')

In [43]:
# df_city_type[(df_city_type['city type'] != 'urban') & (df_city_type['citytype_at_2100'] == 'urban')][['STATEFP', 'NAMELSAD','CensusPop_20',  'city type',
#                                                                                                        'citytype_at_2050', 'citytype_at_2100'
#                                                                                                        ]].sort_values(by = ['citytype_at_2050','city type', 'NAMELSAD'], ascending=False).to_csv(r'outputfiles\csvs\cities_urban_2100.csv')

In [44]:
# df_city_type[(df_city_type['city type'] != 'urban') & (df_city_type['citytype_at_2100'] == 'urban')][['STATEFP', 'NAMELSAD','city type','citytype_at_2050',
#                                                                                                       'citytype_at_2100']].head(65).sort_values(by = ['NAMELSAD','citytype_at_2050','city type', ], ascending=True).reset_index()

In [45]:
# df_city_type[(df_city_type['citytype_at_2050'] != 'urban') & (df_city_type['citytype_at_2100'] == 'urban')][['STATEFP', 'NAMELSAD','CensusPop_20',  'city type',
#                                                                                                        'citytype_at_2050', 'citytype_at_2100'
#                                                                                                        ]].head(65).sort_values(by = ['NAMELSAD','citytype_at_2050','city type', ], ascending=True).reset_index()

In [46]:
# df_city_type[(df_city_type['city type'] != 'urban') & (df_city_type['citytype_at_2050'] == 'urban')][['STATEFP', 'NAMELSAD','CensusPop_20',  'city type',
#                                                                                                        'citytype_at_2050', 'citytype_at_2100'
#                                                                                                        ]].head(60).sort_values(by = ['citytype_at_2050','city type', 'NAMELSAD'], ascending=False)

In [47]:
# df_city_type[(df_city_type['city type'] != 'urban') & (df_city_type['citytype_at_2100'] == 'urban')][['STATEFP', 'NAMELSAD','CensusPop_20',  'city type',
#                                                                                                        'citytype_at_2050', 'citytype_at_2100'
#                                                                                                        ]].head(60).sort_values(by = ['citytype_at_2050','city type', 'NAMELSAD'], ascending=False)